name: PremierRegions
author: Bramsou
version: ${version}
main: fr.premier.regions.RegionsPlugin
api-version: 1.20
libraries:
  - com.zaxxer:HikariCP:5.0.1
  - org.mariadb.jdbc:mariadb-java-client:3.3.3